const root=document.getElementById('app');
const state={token:localStorage.getItem('token')||'',me:null,page:'projects',projects:[],styles:[],users:[],usage:{},models:{text_models:[],image_models:[]},assets:[],selected:null,events:[],artifact:null,tab:'overview',search:'',status:'all',sort:'created_at_desc',styleEdit:null,styleTab:'general',generatedStyle:null,styleIssues:[],styleVersions:[],mediaFilter:'all'};
const STATUS={draft:'Чернетка',queued:'У черзі',processing:'Генерація',review:'На перевірці',changes_requested:'Потрібні зміни',approved:'Схвалено',done:'Готово',error:'Помилка',paused:'Пауза',cancelled:'Скасовано'};
const STAGE={queued:'Очікування запуску',scrape:'Читання сторінки',extract:'Аналіз товару',images:'Підготовка зображень',content:'Створення rich-контенту',review:'Готово до перевірки',approved:'Схвалено',changes_requested:'Потрібні зміни',error:'Помилка',paused:'Призупинено',cancelled:'Скасовано'};
const ROLE_LABEL={admin:'Адміністратор',editor:'Редактор',reviewer:'Рев’юер',viewer:'Перегляд'};
const LANG={ru:'Російська',ua:'Українська',pl:'Польська'}, VARIANT={desktop:'Десктоп',mobile:'Мобільна'};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const LOGO='https://artline.ua/client/images/icons/svg/logo-main-header.svg';
let pendingSave=false;
const money=n=>`$${Number(n||0).toFixed(4)}`, dt=v=>v?new Date(v).toLocaleString('uk-UA'):'—';
async function api(path,opt={}){const h={'Content-Type':'application/json',...(opt.headers||{})};if(state.token)h.Authorization=`Bearer ${state.token}`;const r=await fetch(path,{...opt,headers:h});const t=await r.text();let d=t;try{d=t?JSON.parse(t):null}catch{}if(r.status===401&&path!='/api/auth/login'){localStorage.removeItem('token');state.token='';render();throw Error('Сесію завершено')}if(!r.ok)throw Error(d?.detail||d||`HTTP ${r.status}`);return d}
function toast(text,bad=false){const n=document.createElement('div');n.className=`toast ${bad?'bad':''}`;n.textContent=text;document.body.append(n);setTimeout(()=>n.remove(),3000)}
async function boot(){if(!state.token)return render();await loadAll();render();startLive()}
async function loadAll(){const core=await Promise.all([api('/api/me'),api('/api/projects'),api('/api/styles'),api('/api/usage'),api('/api/models'),api('/api/assets')]);[state.me,state.projects,state.styles,state.usage,state.models,state.assets]=core;if(state.me.role==='admin')state.users=await api('/api/users');if(state.selected)await refreshSelected()}
async function refreshSelected(){const [p,e]=await Promise.all([api(`/api/projects/${state.selected.id}`),api(`/api/projects/${state.selected.id}/events`)]);state.selected=p;state.events=e;selectArtifact(state.artifact?.id,false)}
let live;function startLive(){clearInterval(live);live=setInterval(async()=>{if(!state.token)return;try{state.projects=await api('/api/projects');if(state.selected)await refreshSelected();if(!document.querySelector('dialog[open]')&&!document.activeElement.matches('input,textarea,select')){const y=scrollY;render();scrollTo(0,y)}}catch{}},1800)}
async function login(e){e.preventDefault();const f=new FormData(e.target);try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:f.get('email'),password:f.get('password')})});state.token=d.access_token;localStorage.setItem('token',state.token);await boot()}catch(x){toast(x.message,true)}}
function logout(){localStorage.removeItem('token');location.reload()}
function loginView(){root.innerHTML=`<div class="auth"><form onsubmit="login(event)"><img class="auth-logo" src="${LOGO}" alt="ARTLINE"><h1>Вхід до робочого простору</h1><p>Генерація та керування rich-контентом.</p><label>Email<input name="email" type="email" required></label><label>Пароль<input name="password" type="password" required></label><button class="btn primary">Увійти</button></form></div>`}
function shell(content){const nav=[['projects','Проєкти'],['styles','Стилі'],['media','Медіа'],['usage','Використання'],['users','Користувачі'],['settings','Налаштування']].filter(x=>x[0]!=='users'||state.me?.role==='admin');root.innerHTML=`<div class="shell"><aside><div class="brand-lockup"><img src="${LOGO}" alt="ARTLINE"><small>Rich Studio</small></div><nav>${nav.map(([k,v])=>`<button class="${state.page===k?'active':''}" onclick="go('${k}')">${v}</button>`).join('')}</nav><div class="userbox"><b>${esc(state.me?.name||state.me?.email)}</b><small>${ROLE_LABEL[state.me?.role]||esc(state.me?.role)}</small><button onclick="logout()">Вийти</button></div></aside><main><div class="appbar"><span>Платформа AI rich-контенту</span><span class="api-state">${state.models.source==='openai+configuration'?'Моделі OpenAI синхронізовано':'Моделі з конфігурації'}</span></div><div class="container">${content}</div></main></div>`}
function go(page){state.page=page;state.selected=null;state.styleEdit=null;render()}
function filtered(){let rows=[...state.projects],q=state.search.toLowerCase().trim();if(q)rows=rows.filter(x=>(x.name+' '+x.source_url+' '+x.text_model).toLowerCase().includes(q));if(state.status!=='all')rows=rows.filter(x=>x.status===state.status);const [key,dir]=state.sort.split('_');rows.sort((a,b)=>{let av,bv;if(key==='name'){av=a.name.toLowerCase();bv=b.name.toLowerCase()}else if(key==='cost'){av=a.estimated_cost||0;bv=b.estimated_cost||0}else if(key==='duration'){av=a.duration_seconds||0;bv=b.duration_seconds||0}else{av=new Date(a[key]||0);bv=new Date(b[key]||0)}return (av>bv?1:av<bv?-1:0)*(dir==='asc'?1:-1)});return rows}
function badge(s){return `<span class="badge ${s}">${STATUS[s]||s}</span>`}
function progress(p){return `<div class="progress"><i style="width:${p||0}%"></i></div>`}
function projectsPage(){const rows=filtered();shell(`<header class="pagehead"><div><small class="eyebrow">КЕРУВАННЯ КОНТЕНТОМ ARTLINE</small><h1>Проєкти</h1><p>Вставте посилання на товар — назва визначиться автоматично.</p></div><button class="btn primary" onclick="newProject.showModal()">+ Новий проєкт</button></header><section class="toolbar"><input placeholder="Пошук за назвою, URL або моделлю" value="${esc(state.search)}" oninput="state.search=this.value;render()"><select onchange="state.status=this.value;render()"><option value="all">Усі статуси</option>${Object.entries(STATUS).map(([k,v])=>`<option value="${k}" ${state.status===k?'selected':''}>${v}</option>`).join('')}</select><select onchange="state.sort=this.value;render()"><option value="finished_at_desc">Нещодавно завершені</option><option value="created_at_desc">Спочатку нові</option><option value="created_at_asc">Спочатку старі</option><option value="name_asc">За назвою</option><option value="cost_desc">За вартістю</option><option value="duration_desc">За часом</option></select></section><section class="project-grid">${rows.map(p=>`<article class="project" onclick="openProject('${p.id}')"><div class="project-top">${badge(p.status)}<small>${dt(p.created_at)}</small></div><h3>${esc(p.name)}</h3><p>${esc(p.source_url)}</p><div class="stage-row"><span>${STAGE[p.stage]||'Опрацювання'}</span><b>${p.progress||0}%</b></div>${progress(p.progress)}<div class="project-meta"><span>${esc(p.text_model)}</span><span>${money(p.estimated_cost)}</span><span>${Number(p.duration_seconds||0).toFixed(0)} сек</span></div></article>`).join('')||'<div class="empty">Проєктів поки немає.</div>'}</section>${projectDialog()}`)}
function options(items,selected){return items.map(x=>`<option value="${esc(x)}" ${x===selected?'selected':''}>${esc(x)}</option>`).join('')}
function dataList(id,items){return `<datalist id="${id}">${items.map(x=>`<option value="${esc(x)}"></option>`).join('')}</datalist>`}
function projectDialog(){return `<dialog id="newProject"><form onsubmit="createProject(event)"><div class="dialog-head"><div><small class="eyebrow">НОВИЙ ПРОЄКТ</small><h2>Створити rich-контент</h2></div><button type="button" onclick="newProject.close()">×</button></div><label>Посилання на товар<input name="source_url" type="url" placeholder="https://artline.ua/..." required></label><div class="form-grid"><label>Стиль<select name="style_id">${state.styles.map(s=>`<option value="${s.id}" ${s.is_default?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label>Текстова модель<input name="text_model" list="textModels" value="${esc(state.models.default_text_model||'')}" placeholder="Оберіть або введіть model ID">${dataList('textModels',state.models.text_models||[])}</label><label>Модель зображень<input name="image_model" list="imageModels" value="${esc(state.models.default_image_model||'')}" placeholder="Оберіть або введіть model ID">${dataList('imageModels',state.models.image_models||[])}</label><label>Якість<select name="image_quality"><option>low</option><option selected>medium</option><option>high</option></select></label></div><div class="form-grid"><label>Власне Hero URL <em>необов’язково</em><input name="custom_hero_url" type="url" placeholder="https://..."></label><label>Власне Feature URL <em>необов’язково</em><input name="custom_feature_url" type="url" placeholder="https://..."></label></div><div class="form-grid"><fieldset><legend>Мови</legend><label class="check"><input type="checkbox" name="language" value="ru" checked> Російська</label><label class="check"><input type="checkbox" name="language" value="ua"> Українська</label><label class="check"><input type="checkbox" name="language" value="pl"> Польська</label></fieldset><fieldset><legend>Формати</legend><label class="check"><input type="checkbox" name="variant" value="desktop" checked> Десктоп</label><label class="check"><input type="checkbox" name="variant" value="mobile" checked> Мобільна</label></fieldset></div><button class="btn primary">Створити й запустити</button></form></dialog>`}
async function createProject(e){e.preventDefault();const f=new FormData(e.target),payload={source_url:f.get('source_url'),style_id:f.get('style_id')||null,text_model:f.get('text_model'),image_model:f.get('image_model'),image_quality:f.get('image_quality'),custom_hero_url:f.get('custom_hero_url')||'',custom_feature_url:f.get('custom_feature_url')||'',languages:[...document.querySelectorAll('[name=language]:checked')].map(x=>x.value),variants:[...document.querySelectorAll('[name=variant]:checked')].map(x=>x.value)};try{const p=await api('/api/projects',{method:'POST',body:JSON.stringify(payload)});newProject.close();toast('Проєкт додано до черги');await loadAll();await openProject(p.id)}catch(x){toast(x.message,true)}}
async function openProject(id){state.selected=await api(`/api/projects/${id}`);state.events=await api(`/api/projects/${id}/events`);state.tab='overview';selectArtifact(null,false);render()}
function selectArtifact(id,rerender=true){const list=state.selected?.artifacts||[];state.artifact=(id&&list.find(x=>x.id===id))||state.artifact&&list.find(x=>x.id===state.artifact.id)||list[0]||null;if(rerender)render()}
function workspace(){const p=state.selected,tabs=[['overview','Огляд'],['preview','Перегляд'],['html','HTML'],['assets','Медіа'],['review','Перевірка'],['activity','Історія']];shell(`<header class="project-head"><div><button class="link" onclick="state.selected=null;render()">← Усі проєкти</button><h1>${esc(p.name)}</h1><p>${esc(p.source_url)}</p></div><button class="btn secondary" onclick="rerun()">Повторити генерацію</button></header><section class="live-card"><div class="live-title"><div><span class="pulse"></span><b>${STAGE[p.stage]||'Опрацювання проєкту'}</b></div><strong>${p.progress||0}%</strong></div>${progress(p.progress)}<small>${STATUS[p.status]||p.status}${p.error?' · '+esc(p.error):''}</small></section><section class="metrics"><div><small>Текстова модель</small><b>${esc(p.text_model)}</b></div><div><small>Зображення</small><b>${esc(p.image_model)}</b></div><div><small>Вартість</small><b>${money(p.estimated_cost)}</b></div><div><small>Час</small><b>${Number(p.duration_seconds||0).toFixed(1)} сек</b></div><div><small>Токени</small><b>${(p.input_tokens||0)+(p.output_tokens||0)}</b></div></section><div class="tabs">${tabs.map(([k,v])=>`<button class="${state.tab===k?'active':''}" onclick="state.tab='${k}';render()">${v}</button>`).join('')}</div>${projectTab()}`)}
function projectTab(){if(state.tab==='preview')return preview();if(state.tab==='html')return htmlEditor();if(state.tab==='assets')return projectAssets();if(state.tab==='review')return reviewTab();if(state.tab==='activity')return activity();const p=state.selected;return `<section class="panel"><div class="summary-grid"><div><small>Мови</small><h3>${p.languages.map(x=>LANG[x]).join(', ')}</h3></div><div><small>Формати</small><h3>${p.variants.map(x=>VARIANT[x]).join(', ')}</h3></div><div><small>Категорія</small><h3>${esc(p.product_category||'Визначається')}</h3></div></div><h2>Останні етапи</h2><div class="timeline">${state.events.slice(0,8).map(e=>`<div><time>${dt(e.created_at)}</time><b>${STAGE[e.stage]||'Опрацювання'}</b><span>${esc(e.message)}</span></div>`).join('')||'<p>Подій поки немає.</p>'}</div></section>`}
function artifactSelect(){return `<select onchange="selectArtifact(this.value)">${(state.selected.artifacts||[]).map(a=>`<option value="${a.id}" ${state.artifact?.id===a.id?'selected':''}>${LANG[a.language]} · ${VARIANT[a.variant]} · v${a.version}</option>`).join('')}</select>`}
function resizePreview(frame){try{const doc=frame.contentDocument||frame.contentWindow.document;const h=Math.max(640,doc.documentElement.scrollHeight,doc.body?.scrollHeight||0);frame.style.height=`${h+24}px`}catch{frame.style.height='1200px'}}
function openPreview(){if(!state.artifact?.html)return toast('Немає результату для перегляду',true);const full=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><base href="${location.origin}/"></head><body style="margin:0">${state.artifact.html}</body></html>`;const blob=new Blob([full],{type:'text/html;charset=utf-8'});const url=URL.createObjectURL(blob);const win=window.open(url,'_blank','noopener,noreferrer');if(!win)toast('Браузер заблокував нову вкладку',true);setTimeout(()=>URL.revokeObjectURL(url),60000)}
function preview(){if(!state.artifact)return'<div class="empty">Результат ще не створено.</div>';return `<section class="panel"><div class="panel-tools">${artifactSelect()}<button class="btn secondary" onclick="openPreview()">Відкрити окремо</button></div><div class="preview"><iframe title="Попередній перегляд rich-контенту" sandbox="allow-same-origin" scrolling="no" onload="resizePreview(this)" srcdoc="${esc(state.artifact.html)}"></iframe></div></section>`}
function htmlEditor(){if(!state.artifact)return'<div class="empty">HTML ще не створено.</div>';return `<section class="panel"><div class="panel-tools">${artifactSelect()}<button class="btn primary" onclick="saveHtml(this)">Зберегти нову версію</button></div><textarea id="htmlEditor" class="code">${esc(state.artifact.html)}</textarea></section>`}
function projectAssets(){const a=state.selected.assets||[];return `<section class="media-grid">${a.map(asset=>mediaCard(asset)).join('')||'<div class="empty">Зображень поки немає.</div>'}</section><dialog id="assetDetails"></dialog>`}
function mediaCard(a){return `<article class="media-card"><div class="media-image"><img src="${esc(a.url)}" alt="${esc(a.label)}" loading="lazy"></div><div><span class="badge neutral">${esc(a.label)}</span><h3>${a.width&&a.height?`${a.width} × ${a.height}`:'Зображення'}</h3><p>${esc(a.model||'source')}</p><small>${money(a.cost)} · ${dt(a.created_at)}</small><div class="media-actions"><button class="btn secondary" onclick="showAsset('${a.id}')">Докладніше</button><a class="btn ghost" href="${esc(a.url)}" download>Завантажити</a></div></div></article>`}
function showAsset(id){const a=state.assets.find(x=>x.id===id)||(state.selected?.assets||[]).find(x=>x.id===id);if(!a)return toast('Медіафайл не знайдено',true);let dlg=document.getElementById('assetDetails');if(!dlg){dlg=document.createElement('dialog');dlg.id='assetDetails';document.body.appendChild(dlg)}dlg.innerHTML=`<form method="dialog"><div class="dialog-head"><div><small class="eyebrow">МЕДІАФАЙЛ</small><h2>${esc(a.label||a.kind)}</h2></div><button aria-label="Закрити">×</button></div><div class="asset-detail-image"><img src="${esc(a.url)}" alt="${esc(a.label)}"></div><div class="summary-grid"><div><small>Модель</small><h3>${esc(a.model||'джерело')}</h3></div><div><small>Розмір</small><h3>${a.width&&a.height?`${a.width} × ${a.height}`:'—'}</h3></div><div><small>Вартість</small><h3>${money(a.cost)}</h3></div></div><label>Промпт<textarea rows="8" readonly>${esc(a.prompt||'Промпт не збережено')}</textarea></label><div class="row"><a class="btn primary" href="${esc(a.url)}" target="_blank" rel="noopener">Відкрити оригінал</a><a class="btn secondary" href="${esc(a.url)}" download>Завантажити</a></div></form>`;dlg.showModal()}
function reviewTab(){const labels={facts:'Факти',images:'Зображення',html:'HTML',ru:'Російська',ua:'Українська',mobile:'Мобільна версія'};return `<section class="panel"><h2>Контроль якості</h2><div class="review-grid">${Object.entries(labels).map(([x,label])=>`<label class="check"><input type="checkbox" name="reviewcheck" value="${x}"> ${label}</label>`).join('')}</div><label>Коментар<textarea id="reviewComment" rows="5"></textarea></label><div class="panel-tools review-actions"><button class="btn danger" onclick="review('request_changes',this)">Запросити зміни</button>${['admin','reviewer'].includes(state.me?.role)?`<button class="btn primary" onclick="review('approve',this)">Схвалити</button>`:''}</div></section>`}
function activity(){return `<section class="panel"><h2>Історія проекта</h2><div class="timeline">${state.events.map(e=>`<div><time>${dt(e.created_at)}</time><b>${STAGE[e.stage]||'Опрацювання'}</b><span>${esc(e.message)}</span></div>`).join('')}</div></section>`}
async function rerun(){await api(`/api/projects/${state.selected.id}/run`,{method:'POST'});toast('Генерацію запущено');await refreshSelected();render()}
async function saveHtml(button){if(pendingSave)return;pendingSave=true;const original=button?.textContent;if(button){button.disabled=true;button.textContent='Збереження…'}try{const editor=document.getElementById('htmlEditor');const d=await api(`/api/artifacts/${state.artifact.id}`,{method:'PUT',body:JSON.stringify({html:editor.value})});await refreshSelected();state.artifact=(state.selected.artifacts||[]).find(x=>x.id===d.id)||d;toast(`Збережено версію v${d.version}`);render()}catch(x){toast(x.message,true)}finally{pendingSave=false;if(button){button.disabled=false;button.textContent=original}}}
async function review(decision,button){if(pendingSave)return;pendingSave=true;const original=button?.textContent;if(button){button.disabled=true;button.textContent='Збереження…'}try{const checks=Object.fromEntries([...document.querySelectorAll('[name=reviewcheck]')].map(x=>[x.value,x.checked]));const comment=document.getElementById('reviewComment')?.value||'';const d=await api(`/api/projects/${state.selected.id}/review`,{method:'POST',body:JSON.stringify({decision,comment,checklist:checks})});toast(d.message||'Рішення збережено');await refreshSelected();render()}catch(x){toast(x.message,true)}finally{pendingSave=false;if(button){button.disabled=false;button.textContent=original}}}
function stylesPage(){const s=state.styleEdit||state.styles[0]||{};shell(`<header class="pagehead"><div><small class="eyebrow">РУШІЙ СТИЛІВ</small><h1>Стилі</h1><p>Створюйте, покращуйте та версіонуйте дизайн-код rich-контенту.</p></div><div><button class="btn secondary" onclick="styleGenerator.showModal()">Згенерувати стиль</button><button class="btn primary" onclick="state.styleEdit={};render()">+ Новий стиль</button></div></header><section class="style-shell"><div class="style-list">${state.styles.map(x=>`<button class="${s.id===x.id?'active':''}" onclick="state.styleEdit=state.styles.find(y=>y.id==='${x.id}');render()"><b>${esc(x.name)}</b><small>${x.is_default?'За замовчуванням':'Стиль'}</small></button>`).join('')}</div><div><div class="subtabs">${[['general','Основне'],['html','HTML'],['images','Зображення'],['quality','Якість'],['preview','Перегляд']].map(([k,v])=>`<button class="${state.styleTab===k?'active':''}" onclick="state.styleTab='${k}';render()">${v}</button>`).join('')}</div>${styleEditor(s)}</div></section>${styleGeneratorDialog()}`)}
function styleEditor(s){const score=s.score||{};if(state.styleTab==='preview')return `<section class="panel"><h2>Демонстрація стилю</h2><div class="style-preview">${s.preview_html||'<div class="empty">Перегляд з’явиться після AI-генерації стилю.</div>'}</div></section>`;if(state.styleTab==='quality')return `<section class="panel"><div class="panel-tools"><h2>Якість стилю</h2><div class="row"><button class="btn secondary" onclick="analyzeStyle()">Перевірити стиль</button>${s.id?`<button class="btn ghost" onclick="loadStyleVersions('${s.id}')">Історія версій</button>`:''}</div></div><div class="metrics"><div><small>Узгодженість</small><b>${score.consistency||'—'}</b></div><div><small>Читабельність</small><b>${score.readability||'—'}</b></div><div><small>Відповідність ARTLINE</small><b>${score.brand_fit||'—'}</b></div></div>${state.styleIssues.length?`<div class="issue-list">${state.styleIssues.map(x=>`<div>${esc(x)}</div>`).join('')}</div>`:''}${state.styleVersions.length?`<div class="version-list">${state.styleVersions.map(v=>`<button onclick="restoreStyleVersion(${v.version})"><b>v${v.version}</b><small>${dt(v.created_at)}</small></button>`).join('')}</div>`:''}${s.id?`<label>Що покращити<textarea id="improveInstructions" rows="5" placeholder="Наприклад: зробити Hero преміальнішим і зменшити візуальний шум"></textarea></label><button class="btn primary" onclick="improveStyle('${s.id}')">Покращити стиль через AI</button>`:''}</section>`;return `<form class="panel" onsubmit="saveStyle(event)"><input type="hidden" name="id" value="${esc(s.id||'')}">${state.styleTab==='general'?`<label>Назва<input name="name" value="${esc(s.name||'')}" required></label><label>Опис<textarea name="description" rows="5">${esc(s.description||'')}</textarea></label><label class="check"><input type="checkbox" name="is_default" ${s.is_default?'checked':''}> Використовувати за замовчуванням</label>`:''}${state.styleTab==='html'?`<label>Єдиний Style Prompt<textarea name="prompt" rows="24">${esc(s.prompt||'')}</textarea></label>`:''}${state.styleTab==='images'?`<label>Промпт Hero <em>необов’язково</em><textarea name="hero_prompt" rows="10">${esc(s.hero_prompt||'')}</textarea></label><label>Промпт Feature <em>необов’язково</em><textarea name="feature_prompt" rows="10">${esc(s.feature_prompt||'')}</textarea></label><label>Негативний промпт<textarea name="negative_prompt" rows="7">${esc(s.negative_prompt||'')}</textarea></label>`:''}<button class="btn primary">Зберегти стиль</button></form>`}
function collectStyleForm(f){const base=state.styleEdit||state.styles[0]||{};return {name:f.get('name')||base.name||'Новий стиль',description:f.get('description')??base.description??'',prompt:f.get('prompt')??base.prompt??'',hero_prompt:f.get('hero_prompt')??base.hero_prompt??'',feature_prompt:f.get('feature_prompt')??base.feature_prompt??'',negative_prompt:f.get('negative_prompt')??base.negative_prompt??'',score:base.score||{},preview_html:base.preview_html||'',is_default:state.styleTab==='general'?f.get('is_default')==='on':!!base.is_default}}
async function saveStyle(e){e.preventDefault();if(pendingSave)return;pendingSave=true;const button=e.submitter;const original=button?.textContent;if(button){button.disabled=true;button.textContent='Збереження…'}const f=new FormData(e.target),id=f.get('id'),payload=collectStyleForm(f);try{const d=await api(id?`/api/styles/${id}`:'/api/styles',{method:id?'PUT':'POST',body:JSON.stringify(payload)});state.styles=await api('/api/styles');state.styleEdit=state.styles.find(x=>x.id===(d.id||id))||state.styles[0];toast('Стиль збережено');render()}catch(x){toast(x.message,true)}finally{pendingSave=false;if(button){button.disabled=false;button.textContent=original}}}
function styleGeneratorDialog(){return `<dialog id="styleGenerator"><form onsubmit="generateStyle(event)"><div class="dialog-head"><div><small class="eyebrow">AI-ГЕНЕРАТОР СТИЛІВ</small><h2>Створити дизайн-стиль</h2></div><button type="button" onclick="styleGenerator.close()">×</button></div><label>Назва<input name="name" value="ARTLINE Premium" required></label><label>Опис бажаного результату<textarea name="brief" rows="8" placeholder="Категорія товару, настрій, структура блоків, рівень преміальності, обмеження..."></textarea></label><div class="form-grid"><label>Категорія<input name="category" placeholder="3D-принтери, енергетика, ігрові ПК..."></label><label>Настрій<input name="mood" placeholder="Преміальний, технічний, мінімалістичний..."></label></div><label>URL-референс <em>необов’язково</em><input name="reference_url" type="url"></label><label>Модель<input name="model" list="styleModels" value="${esc(state.models.default_text_model||'')}">${dataList('styleModels',state.models.text_models||[])}</label><button class="btn primary">Згенерувати</button></form></dialog>`}
async function generateStyle(e){e.preventDefault();const f=new FormData(e.target);try{const payload=Object.fromEntries(f);payload.brief=[payload.brief,payload.category&&`Category: ${payload.category}`,payload.mood&&`Mood: ${payload.mood}`].filter(Boolean).join('\n');const d=await api('/api/styles/generate',{method:'POST',body:JSON.stringify(payload)});state.styleEdit={name:f.get('name'),description:d.description,prompt:d.style_prompt,hero_prompt:d.hero_prompt,feature_prompt:d.feature_prompt,negative_prompt:d.negative_prompt,score:d.score,preview_html:d.preview_html,is_default:false};styleGenerator.close();state.styleTab='preview';toast('Стиль згенеровано');render()}catch(x){toast(x.message,true)}}
async function analyzeStyle(){const s=state.styleEdit||{};try{const d=await api('/api/styles/analyze',{method:'POST',body:JSON.stringify({prompt:s.prompt||'',hero_prompt:s.hero_prompt||'',feature_prompt:s.feature_prompt||'',negative_prompt:s.negative_prompt||''})});state.styleEdit={...s,score:d.score};state.styleIssues=d.issues||[];toast(d.ready?'Стиль готовий до роботи':'Є рекомендації щодо покращення',!d.ready);render()}catch(x){toast(x.message,true)}}
async function loadStyleVersions(id){try{state.styleVersions=await api(`/api/styles/${id}/versions`);render()}catch(x){toast(x.message,true)}}
function restoreStyleVersion(version){const v=state.styleVersions.find(x=>x.version===version);if(!v)return;state.styleEdit={...state.styleEdit,prompt:v.prompt,hero_prompt:v.hero_prompt,feature_prompt:v.feature_prompt};state.styleTab='html';toast(`Завантажено версію v${version}`);render()}
async function improveStyle(id){try{const d=await api(`/api/styles/${id}/improve`,{method:'POST',body:JSON.stringify({instructions:improveInstructions.value,model:state.models.default_text_model})});state.styleEdit={...state.styleEdit,description:d.description,prompt:d.style_prompt,hero_prompt:d.hero_prompt,feature_prompt:d.feature_prompt,negative_prompt:d.negative_prompt,score:d.score,preview_html:d.preview_html};state.styleTab='preview';toast('Покращена версія готова');render()}catch(x){toast(x.message,true)}}
function mediaPage(){const kinds=['all',...new Set(state.assets.map(x=>x.kind||x.label||'image'))],rows=state.mediaFilter==='all'?state.assets:state.assets.filter(x=>(x.kind||x.label)===state.mediaFilter);shell(`<header class="pagehead"><div><small class="eyebrow">МЕДІАТЕКА</small><h1>Медіа</h1><p>Усі вихідні, власні та згенеровані зображення.</p></div></header><section class="toolbar media-toolbar"><select onchange="state.mediaFilter=this.value;render()">${kinds.map(x=>`<option value="${esc(x)}" ${state.mediaFilter===x?'selected':''}>${x==='all'?'Усі зображення':esc(x)}</option>`).join('')}</select><div></div><b>${rows.length} файлів</b></section><section class="media-grid">${rows.map(mediaCard).join('')||'<div class="empty">Галерея порожня.</div>'}</section><dialog id="assetDetails"></dialog>`) }
function usagePage(){shell(`<header class="pagehead"><div><small class="eyebrow">ВИКОРИСТАННЯ</small><h1>Використання</h1><p>Час, токени та приблизна вартість.</p></div></header><section class="metrics large"><div><small>Загальна вартість</small><b>${money(state.usage.total_cost)}</b></div><div><small>Проєкти</small><b>${state.usage.projects||0}</b></div><div><small>Вхідні токени</small><b>${state.usage.input_tokens||0}</b></div><div><small>Вихідні токени</small><b>${state.usage.output_tokens||0}</b></div><div><small>Зображення</small><b>${state.usage.images||0}</b></div></section>`)}
function usersPage(){shell(`<header class="pagehead"><div><small class="eyebrow">ДОСТУП</small><h1>Користувачі</h1><p>Створюйте облікові записи безпосередньо або запрошуйте за посиланням.</p></div><div><button class="btn secondary" onclick="inviteDialog.showModal()">Запросити</button><button class="btn primary" onclick="createUserDialog.showModal()">+ Створити користувача</button></div></header><section class="panel table-wrap"><table><thead><tr><th>Користувач</th><th>Роль</th><th>Активний</th><th>Останній вхід</th><th>Дії</th></tr></thead><tbody>${state.users.map(u=>`<tr><td><b>${esc(u.name||u.email)}</b><small>${esc(u.email)}</small></td><td><select onchange="updateUser('${u.id}','role',this.value)">${['admin','editor','reviewer','viewer'].map(r=>`<option value="${r}" ${u.role===r?'selected':''}>${ROLE_LABEL[r]}</option>`).join('')}</select></td><td><input type="checkbox" ${u.active?'checked':''} onchange="updateUser('${u.id}','active',this.checked)"></td><td>${dt(u.last_login_at)}</td><td><div class="row"><button class="btn ghost" onclick="resetPassword('${u.id}')">Пароль</button>${u.id!==state.me.id?`<button class="btn danger" onclick="deleteUser('${u.id}')">Видалити</button>`:''}</div></td></tr>`).join('')}</tbody></table></section>${userDialogs()}`)}
function userDialogs(){return `<dialog id="createUserDialog"><form onsubmit="createUser(event)"><div class="dialog-head"><h2>Створити користувача</h2><button type="button" onclick="createUserDialog.close()">×</button></div><label>Ім’я<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Пароль<input name="password" type="password" minlength="8" required></label><label>Роль<select name="role"><option value="editor">Редактор</option><option value="reviewer">Рев’юер</option><option value="viewer">Перегляд</option><option value="admin">Адміністратор</option></select></label><button class="btn primary">Створити</button></form></dialog><dialog id="inviteDialog"><form onsubmit="inviteUser(event)"><div class="dialog-head"><h2>Запросити користувача</h2><button type="button" onclick="inviteDialog.close()">×</button></div><label>Email<input name="email" type="email" required></label><label>Роль<select name="role"><option value="editor">Редактор</option><option value="reviewer">Рев’юер</option><option value="viewer">Перегляд</option><option value="admin">Адміністратор</option></select></label><button class="btn primary">Створити посилання</button></form></dialog>`}
async function createUser(e){e.preventDefault();try{await api('/api/users',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});createUserDialog.close();state.users=await api('/api/users');toast('Користувача створено');render()}catch(x){toast(x.message,true)}}
async function inviteUser(e){e.preventDefault();try{const d=await api('/api/users/invites',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});inviteDialog.close();prompt('Посилання для реєстрації',location.origin+d.register_path)}catch(x){toast(x.message,true)}}
async function updateUser(id,key,value){await api(`/api/users/${id}`,{method:'PATCH',body:JSON.stringify({[key]:value})});state.users=await api('/api/users');render()}
async function resetPassword(id){const password=prompt('Новий пароль (щонайменше 8 символів)');if(!password)return;try{await api(`/api/users/${id}/password`,{method:'POST',body:JSON.stringify({password})});toast('Пароль оновлено')}catch(x){toast(x.message,true)}}
async function deleteUser(id){if(!confirm('Видалити користувача?'))return;try{await api(`/api/users/${id}`,{method:'DELETE'});state.users=await api('/api/users');toast('Користувача видалено');render()}catch(x){toast(x.message,true)}}
function settingsPage(){shell(`<header class="pagehead"><div><small class="eyebrow">НАЛАШТУВАННЯ</small><h1>Налаштування</h1><p>Моделі завантажуються з OpenAI API та доповнюються конфігурацією.</p></div><button class="btn secondary" onclick="reloadModels()">Оновити список моделей</button></header><section class="two"><div class="panel"><h2>Текстові моделі</h2><p>Джерело: <b>${esc(state.models.source)}</b></p><div class="model-list">${state.models.text_models.map(x=>`<code>${esc(x)}</code>`).join('')}</div></div><div class="panel"><h2>Моделі зображень</h2><div class="model-list">${state.models.image_models.map(x=>`<code>${esc(x)}</code>`).join('')}</div><h2>Моделі міркування</h2><div class="model-list">${(state.models.reasoning_models||[]).map(x=>`<code>${esc(x)}</code>`).join('')||'<small>Окремих reasoning-моделей немає.</small>'}</div></div></section>`) }
async function reloadModels(){try{state.models=await api('/api/models');toast('Список моделей оновлено');render()}catch(x){toast(x.message,true)}}
function render(){if(!state.token)return loginView();if(state.selected)return workspace();({projects:projectsPage,styles:stylesPage,media:mediaPage,usage:usagePage,users:usersPage,settings:settingsPage}[state.page]||projectsPage)()}
boot().catch(e=>{console.error(e);toast(e.message,true);render()});
